### PR TITLE
Removing Service metadata from deployment-env.yml file

### PR DESCRIPTION
**Pull request by SiniWilson**
### Requirements

[CAPI-1000](https://tmobile.atlassian.net/browse/CAPI-1000) : Move services metadata from deployment-env to services catalog

### Description of the Change

- Removed service metadata from deployment.yml file 
- Saved the information in DB
- Replaced Service_id in deployment.yml file

### Possible Drawbacks

User no longer be able to see the service's metadata information. Instead he can see only the service ID

### CODE REVIEW

**Comment by suryajak** [comment]
Are these changes also part of the other PR you have open?

**Comment by SiniWilson** [comment]
Yes Surya. But some of them are not my changes. Especially related to the platform_email service

**Comment by SiniWilson** [comment]
These changes are also part of the PR https://github.com/tmobile/jazz/pull/61/

**Comment by SiniWilson** [comment]
Only in ServiceOnboarding build pack have change relating to this PR 
https://github.com/tmobile/jazz/pull/72/files#diff-19b0ab334d3755599c34e644130e652dR176

**Comment by suryajak** [comment]
It is impossible to review this PR with 92 files and 150 commits. Please resubmit this PR by rebasing your fork and submitting only files that have changed.

**Comment by suryajak** [comment]
@SiniWilson: closing this old PR

**Pull request closed without merging**
